version: 2

sources:
  - name: staging
    database: prefect-de-zoomcamp-402615
    schema: trips_data_all.green_tripdata

    tables:
       - name: green_tripdata
       - name: yellow_tripdata
       